# -*- coding: utf-8 -*-
"""number guessing game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AKPszYEaT7Vagrmvblc8p-EzIPBjSjCt
"""

import random

# generate a random number between 1 and 100
guess_by_comp = random.randint(1, 100)

# initialize the number of guesses to 0
num_guesses = 0

# ask the user to guess the number
while True:
    guessed_by_user = input("Guess a number between 1 and 100, or type 'exit' to quit: ")
    
    # check if the user wants to quit
    if guess.lower() == 'q':
        print("Thanks for playing! The correct number was", number)
        break
    
    num_guesses += 1
    
    # check if the guess is correct
    if int(guessed_by_user) == guess_by_comp:
      print("Congratulations, you guessed the number in", num_guesses, "guesses!")
      break
    # if the guess is too high or too low, provide feedback to the user
    elif int(guessed_by_user) < guess_by_comp:
      print("Your guess is too low, try again.")
    else:
      print("Your guess is too high, try again.")